#!/bin/bash

if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then

	echo "Usage:

 unmount <MOUNTPOINT>
   MOUNTPOINT - any mountpoint, could be by name or path. eg:
     unmount mountplace

   If above fails, the following will be tried automatically:
     unmount /mnt/MOUNTPOINT
     unmount /media/$USER/MOUNTPOINT
"
	exit 0

else

	mountpoint -q $1 && sudo umount $1 && exit 0
	mountpoint -q /mnt/$1 && sudo umount /mnt/$1 && exit 0
	mountpoint -q /media/$USER/$1 && sudo umount /media/$USER/$1 && exit 0
	exit 0

fi
